# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a99d928a734e3929b20ea780518012d48f377e48a1692f6b7a6c1f55cfd66007008b9cd6362d0c7dba4b58ec132c9db4ee092b084b19ad0c34e8a0e0a3a5893e

test:
  secret_key_base: e8bddc2162196cc9cfc74b1041ddd3a7cecb5c2a2aeccaeda14ebab157f99a4bb9b1d9cddeb0c361fdd8eea42798507007da60fe5362803d444f0a9757104f06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
